# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xvHFJPRcYnsa5_Bif1Pb-l1NnGt6o2Tt

# Inicio Notebook
"""

a = 35
a



b = [1,2,3,4]
b.append("oi")

b

import pandas as pd
pd.read_csv('/content/drive/My Drive/Colab Notebooks/ECM514/Datasets/iris.data')

df.head())

